### ISSUE TITLE
Replace `Zn:getInteger()` usage with `Zn:asInteger()`

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/math#107]
So since `RingElement` recently got the new `asInteger` method, we should use that one instead of the `Zn`-specific `getInteger` method. Then we can remove `getInteger`.

**Comment by rheitjoh** [comment]
@JanBobolz is this ok btw? I am asking because `getInteger` explicitly states that it returns an integer in [0,n), while `asInteger` just states that it inverts the whole `getElement` method, meaning `asInteger` could theoretically return something greater than n as long as it is still in the same equivalence class. Maybe we should clarify that or is there meant to be a difference?

**Comment by JanBobolz** [comment]
No difference intendend. You can add to the Javadoc for `asInteger` that the result will be between 0 and the ring's characteristic.
