### ISSUE TITLE
Add own workflows for android tests

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/math#115]
As suggested by @feidens we should add own workflows for the android compatibility tests.
One of the reasons for this is that running these tests on every commit is very slow and slows down the CI a lot.
Plus then we can have separate badges in the readme.

**Comment by feidens** [comment]
Fixed in a5bb43846718879dfcfb5b647ad2702dba0ddc40

**Comment by feidens** [comment]
Badge is missing
