### ISSUE TITLE
Rename getFoo(Representation) to restoreFoo(Representation)

### ISSUE THREAD

**Issue by JanBobolz** [cryptimeleon/math#53]
See title.

**Comment by JanBobolz** [comment]
Same for other projects

**Comment by rheitjoh** [comment]
Do we also want to rename the `RepresentationRestorer` interface method `recreateFromRepresentation` to `restoreFromRepresentation`? That would be more consistent.

**Comment by JanBobolz** [comment]
Fixed by https://github.com/cryptimeleon/math/pull/57
