### ISSUE TITLE
Optimize final Exponentation of BN

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/math#81]
(This issue has been imported from the Gitlab repository because it seems to not have been addressed yet.)

## Original Text (Issue [203](https://git.cs.uni-paderborn.de/ag-bloemer/sis/-/issues/203))

View on [Gitlab](https://git.cs.uni-paderborn.de/ag-bloemer/sis/-/issues/203) as there is a lot of math formatting.

**Comment by rheitjoh** [comment]
This one might have very well been addressed already, not sure.

**Comment by JanBobolz** [comment]
https://github.com/cryptimeleon/math/pull/46/commits/ab14ec184debf8f9d6e52b825d82d9bbd56e3ea1
